#!/usr/bin/env python3
"""Compare sparse vs dense reward ablation results."""

from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


def _load_summary(log_dir: Path) -> dict[str, Any]:
    """Load summary.json from an evaluation log directory."""
    summary_path = log_dir / "summary.json"
    if not summary_path.exists():
        logger.warning("Summary not found: %s", summary_path)
        return {}
    return json.loads(summary_path.read_text())


def generate_reward_ablation(
    validation_inputs: list[Path],
    test_inputs: list[Path],
    output_path: Path,
) -> None:
    """Generate reward ablation report.

    Args:
        validation_inputs: List of validation eval log directories.
        test_inputs: List of test eval log directories.
        output_path: Path to write the report.
    """
    rows: list[dict[str, Any]] = []

    for val_dir, test_dir in zip(validation_inputs, test_inputs):
        val_summary = _load_summary(val_dir)
        test_summary = _load_summary(test_dir)

        # Determine reward mode from directory name
        name = val_dir.name
        if "sparse" in name:
            reward = "Sparse"
        elif "dense" in name:
            reward = "Dense"
        else:
            reward = name

        rows.append({
            "Reward": reward,
            "Val Private Pass": val_summary.get("private_pass_rate", "N/A"),
            "Test Hidden Pass": test_summary.get("hidden_pass_rate", "N/A"),
            "Invalid Action": val_summary.get("avg_invalid_actions", "N/A"),
            "Invalid Edit": val_summary.get("avg_invalid_edits", "N/A"),
            "Avg Steps": val_summary.get("avg_steps", "N/A"),
        })

    # Generate markdown table
    lines = ["# Reward Ablation", ""]

    headers = ["Reward", "Val Private Pass", "Test Hidden Pass", "Invalid Action", "Invalid Edit", "Avg Steps"]
    lines.append("| " + " | ".join(headers) + " |")
    lines.append("| " + " | ".join(["---"] * len(headers)) + " |")

    for row in rows:
        vals = []
        for h in headers:
            v = row.get(h, "N/A")
            if isinstance(v, float):
                vals.append(f"{v:.3f}")
            else:
                vals.append(str(v))
        lines.append("| " + " | ".join(vals) + " |")

    lines.append("")
    lines.append("Generated by `scripts/compare_rewards.py`")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines))
    logger.info("Reward ablation written to %s", output_path)


def main() -> None:
    parser = argparse.ArgumentParser(description="Compare reward ablation results")
    parser.add_argument(
        "--validation-inputs", nargs="+", type=Path, required=True,
        help="Validation eval log directories",
    )
    parser.add_argument(
        "--test-inputs", nargs="+", type=Path, required=True,
        help="Test eval log directories",
    )
    parser.add_argument("--output", type=Path, required=True, help="Output report path")

    args = parser.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

    generate_reward_ablation(
        validation_inputs=args.validation_inputs,
        test_inputs=args.test_inputs,
        output_path=args.output,
    )


if __name__ == "__main__":
    main()
